#!/usr/bin/env bash
# displays a list of currently running processes.
# show all processes, for all users, including those
# which might not have a TTY
# Displaying in a user-oriented format
# Showing  process hierarchy

ps -auxf
